### ISSUE TITLE
Filter out Target worlds

### ISSUE THREAD

**Issue by Z7-z** [Cgende/World-Finder#1]
Currently target worlds aren't filtered out so when it does hop to a target world, you get this needless 'warning' from Jagex that you have to click through to get to the world, it's so annoying it would be so nice if you could just filter them out so it doesn't hop to them. 

I will attach a picture of the notice it gives you before hopping to it, usually people hop for shopscape or to get an empty space somewhere, so the notice is so pointless anyway. 
https://i.imgur.com/6Zxb88t.png

**Comment by Conrad33** [comment]
Added in e72f95332c948dc8494ac3a9942453cacdbe1332. 

This adds:
- ability to filter specific skill total/Target/High risk worlds
- ability to filter by max ping
- Quick Hop will no longer hop to filtered worlds

It just needs to be accepted by the RuneLite team, which could take a week or two. 
You can check the status here: [#4262](https://github.com/runelite/plugin-hub/pull/4262)

Please let me know if you run into any issues once its live.

**Comment by Z7-z** [comment]
sweet baby jesus great work sir
