### ISSUE TITLE
Suggestion: filtering

### ISSUE THREAD

**Issue by Raisoshi** [Cgende/World-Finder#2]
I've always wanted a plug-in that could filter out worlds based on different criteria, if this could be it it would be awesome.

For example: worlds with less than 50ms ping, in the US filter out 1500, 1750, 2000, 2200, target, pvp and high risk worlds.

These would be all separate filters applied and it would make it look so clean when trying to pick a world that meets those criteria

**Comment by Conrad33** [comment]
Added in e72f95332c948dc8494ac3a9942453cacdbe1332. 

This adds:
- ability to filter specific skill total/Target/High risk worlds
- ability to filter by max ping
- Quick Hop will no longer hop to filtered worlds

It just needs to be accepted by the RuneLite team, which could take a week or two. 
You can check the status here: [#4262](https://github.com/runelite/plugin-hub/pull/4262)

Please let me know if you run into any issues once its live.
